export const RECEIVE_INCREMENT = 'RECEIVE_INCREMENT';
export type RECEIVE_INCREMENT = typeof RECEIVE_INCREMENT;

export const RECEIVE_DECREMENT = 'RECEIVE_DECREMENT';
export type RECEIVE_DECREMENT = typeof RECEIVE_DECREMENT;