export const RECEIVE_HOMENEWS_DATA = 'RECEIVE_HOMENEWS_DATA';
export type RECEIVE_HOMENEWS_DATA = typeof RECEIVE_HOMENEWS_DATA;

export const CHANGE_NEWSDATA_LOADING = 'CHANGE_NEWSDATA_LOADING';
export type CHANGE_NEWSDATA_LOADING = typeof CHANGE_NEWSDATA_LOADING;