export const SAVE_SEARCH_HISTORY = 'SAVE_SEARCH_HISTORY';
export type SAVE_SEARCH_HISTORY = typeof SAVE_SEARCH_HISTORY;

export const EMPTY_SEARCH_HISTORY = 'EMPTY_SEARCH_HISTORY';
export type EMPTY_SEARCH_HISTORY = typeof EMPTY_SEARCH_HISTORY;