export const RECEIVE_VIDEO_DATA = 'RECEIVE_VIDEO_DATA';
export type RECEIVE_VIDEO_DATA = typeof RECEIVE_VIDEO_DATA;

export const CHANGE_VIDEO_LOADING = 'CHANGE_VIDEO_LOADING';
export type CHANGE_VIDEO_LOADING = typeof CHANGE_VIDEO_LOADING;